# Generated by Django 5.0.1 on 2024-01-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_preparation_time_unity_recipe_preparation_time_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_unity',
            new_name='servings_unit',
        ),
    ]
